### PR TITLE
Glyn's benchmarks

### PR DESCRIPTION
**Pull request by glyn**
I was intrigued, so I first of all measured the performance on my desktop machine. I then tried some inlining, loop unrolling, and even avoiding allocating vectors unnecessarily in `squeeze()` (since `r==1`). All of these made only marginal improvements in performance. Aside from profiling, I don't know what to suggest, but the code looks reasonable to me.

### CODE REVIEW

**Comment by atoponce** [comment]
Thanks!

**Comment by glyn** [comment]
Huh! I don't mind this PR having been merged, but I hope you noticed it was a _draft PR_ - I was only wanting to compare notes.

**Comment by atoponce** [comment]
Heh. Fair. I'm not good at the GitHub work flows. I can revert. Regardless, thanks for looking over the code.

**Comment by glyn** [comment]
No need to revert. More data is goodness. Interesting how spritz performed relatively well on my machine. I was using a recent version of Rust...

**Comment by atoponce** [comment]
Interestingly enough, I got into work and checked the benchmarks on my AMD Ryzen 5 3400G with Radeon Vega Graphics (after making a performance bug fix to RC4A):

| PRNG | MBps |
|---|:---:|
| RC4 | 366.13 |
| RC4A | 349.17 |
| RC4+ | 361.86 |
| VMPC | 266.43 |
| Spritz | 62.44 |

**Comment by atoponce** [comment]
RC4A is designed with 2 states such that it can be parallelized. So I guess the next skill to learn is threading in Rust and make RC4A multi-threaded.

**Pull request merged**
